import { FillInBlankExercise } from './types';

/**
 * Sample data for Fill-in-the-Blank exercises
 * This file contains example data that demonstrates the structure expected
 * for Fill-in-the-Blank exercises.
 * 
 * AI-INTEGRATION-NOTE: This sample data illustrates where AI-generated content
 * will be inserted. The actual content will be generated by Alex Ex's system.
 */

/**
 * Example of a basic fill-in-the-blank exercise
 */
export const basicFillInBlankExample: FillInBlankExercise = {
  id: "fib-example-1",
  
  // AI-INTEGRATION-POINT: Instructions text
  instructions: "Fill in the blanks with the correct words.",
  
  // AI-INTEGRATION-POINT: Passage text with embedded blank markers
  // Format: {{blank:id:default-answer}}
  passage: "The Declaration of Independence was adopted by the Continental Congress on {{blank:1:July 4, 1776}}. It announced that the {{blank:2:thirteen American colonies}} were now independent states.",
  
  // AI-INTEGRATION-POINT: Blanks array with accepted answers and feedback
  blanks: [
    {
      id: "1",
      // AI-INTEGRATION-POINT: Multiple accepted variations of the correct answer
      acceptedAnswers: ["July 4, 1776", "July 4 1776", "4 July 1776", "4th of July 1776"],
      // AI-INTEGRATION-POINT: Optional hint
      hint: "Think about Independence Day.",
      // AI-INTEGRATION-POINT: Optional feedback specific to this blank
      feedback: "July 4, 1776 is celebrated as Independence Day in the United States."
    },
    {
      id: "2",
      acceptedAnswers: ["thirteen American colonies", "13 American colonies", "American colonies"],
      hint: "How many colonies declared independence?",
      feedback: "The thirteen American colonies formed the original United States."
    }
  ],
  
  // AI-INTEGRATION-POINT: Explanation shown after submission
  explanation: "The Declaration of Independence was adopted on July 4, 1776, and announced that the thirteen American colonies were now independent from Great Britain.",
  
  // Whether to use case-sensitive matching
  caseSensitive: false
};

/**
 * Example of a more complex fill-in-the-blank exercise with multiple blanks
 */
export const complexFillInBlankExample: FillInBlankExercise = {
  id: "fib-example-2",
  
  instructions: "Complete the code snippet by filling in the blanks with the correct JavaScript syntax.",
  
  passage: `function calculateArea() {
  const length = {{blank:1:parseFloat}}(document.getElementById('length').value);
  const width = {{blank:2:parseFloat}}(document.getElementById('width').value);
  
  if ({{blank:3:isNaN}}(length) || {{blank:4:isNaN}}(width)) {
    return "Please enter valid numbers";
  }
  
  const area = length {{blank:5:*}} width;
  return "The area is " + area + " square units";
}`,
  
  blanks: [
    {
      id: "1",
      acceptedAnswers: ["parseFloat", "Number", "parseInt"],
      hint: "You need to convert the string to a number.",
      feedback: "parseFloat() converts a string to a floating-point number."
    },
    {
      id: "2",
      acceptedAnswers: ["parseFloat", "Number", "parseInt"],
      hint: "You need to convert the string to a number.",
      feedback: "parseFloat() converts a string to a floating-point number."
    },
    {
      id: "3",
      acceptedAnswers: ["isNaN"],
      hint: "You need to check if the value is Not a Number.",
      feedback: "isNaN() checks if a value is Not a Number."
    },
    {
      id: "4",
      acceptedAnswers: ["isNaN"],
      hint: "You need to check if the value is Not a Number.",
      feedback: "isNaN() checks if a value is Not a Number."
    },
    {
      id: "5",
      acceptedAnswers: ["*"],
      hint: "You need to multiply the length and width.",
      feedback: "The * operator multiplies two numbers."
    }
  ],
  
  explanation: "This function calculates the area of a rectangle by getting the length and width from input fields, converting them to numbers using parseFloat(), checking if they are valid numbers using isNaN(), and then multiplying them to get the area.",
  
  caseSensitive: true
};

/**
 * Example of a fill-in-the-blank exercise for language learning
 */
export const languageFillInBlankExample: FillInBlankExercise = {
  id: "fib-example-3",
  
  instructions: "Complete the French sentences by filling in the blanks with the correct words.",
  
  passage: `1. Je {{blank:1:m'appelle}} Marie.
2. Il {{blank:2:fait}} beau aujourd'hui.
3. Nous {{blank:3:allons}} au cinéma ce soir.
4. Vous {{blank:4:parlez}} français très bien!`,
  
  blanks: [
    {
      id: "1",
      acceptedAnswers: ["m'appelle"],
      hint: "The verb is 's'appeler' (to call oneself).",
      feedback: "Je m'appelle = My name is (literally: I call myself)."
    },
    {
      id: "2",
      acceptedAnswers: ["fait"],
      hint: "The verb is 'faire' (to do/make).",
      feedback: "Il fait beau = The weather is nice (literally: It makes beautiful)."
    },
    {
      id: "3",
      acceptedAnswers: ["allons"],
      hint: "The verb is 'aller' (to go).",
      feedback: "Nous allons = We are going."
    },
    {
      id: "4",
      acceptedAnswers: ["parlez"],
      hint: "The verb is 'parler' (to speak).",
      feedback: "Vous parlez = You speak."
    }
  ],
  
  explanation: "These sentences use common French verbs: s'appeler (to call oneself), faire (to do/make), aller (to go), and parler (to speak). The verbs are conjugated according to the subject of the sentence.",
  
  caseSensitive: false
};

// Helper function to transform API response data to our internal structure
export const transformApiResponseToFillInBlank = (apiData: any): FillInBlankExercise => {
  // AI-INTEGRATION-POINT: This function will convert the data format
  // from Alex's AI generation to our internal format
  
  return {
    id: apiData.id || `fib-${Date.now()}`,
    instructions: apiData.instructions || "Fill in the blanks with the correct words.",
    passage: apiData.passage || "",
    blanks: (apiData.blanks || []).map((blank: any) => ({
      id: blank.id,
      acceptedAnswers: Array.isArray(blank.acceptedAnswers) 
        ? blank.acceptedAnswers 
        : [blank.acceptedAnswers],
      hint: blank.hint,
      feedback: blank.feedback
    })),
    explanation: apiData.explanation || "",
    caseSensitive: apiData.case_sensitive || false
  };
};