import React from 'react';
import { OptionsListProps } from './types';
import OptionItem from './OptionItem';

/**
 * Component for displaying a list of options in a Multiple Choice exercise
 * 
 * @component
 */
const OptionsList: React.FC<OptionsListProps> = ({
  options,
  allowMultipleSelections,
  selectedOptionIds,
  onOptionSelect,
  showFeedback
}) => {
  return (
    <div className="mb-6">
      {/* 
        Map through the options array and render an OptionItem for each one
        AI-INTEGRATION-POINT: This component expects the options array 
        to be generated by Alex's AI system
      */}
      {options.map((option) => (
        <OptionItem
          key={option.id}
          option={option}
          isSelected={selectedOptionIds.includes(option.id)}
          isMultipleSelect={allowMultipleSelections}
          onSelect={() => {
            if (!showFeedback) {
              onOptionSelect(option.id);
            }
          }}
          showFeedback={showFeedback}
        />
      ))}
    </div>
  );
};

export default OptionsList;
