import React, { useState, useEffect } from 'react';
import { MultipleChoiceExercise, transformApiResponseToMultipleChoice } from '../exercises/multiple-choice';
import { 
  FillInBlankExercise, 
  WordSelector, 
  transformApiResponseToFillInBlank, 
  generatePassageWithBlanks 
} from '../exercises/fill-in-blank';
import sampleExercises from '../exercises/fill-in-blank/sampleData';

/**
 * ExerciseTester - A split-screen testing environment for exercise components
 * 
 * Left side: Teacher input and controls
 * Right side: Exercise preview with debug information
 */
const ExerciseTester = () => {
  // State for tracking the selected exercise type
  const [exerciseType, setExerciseType] = useState('multiple_choice');
  
  // State for teacher input text
  const [inputText, setInputText] = useState('');
  
  // State for selected words (for fill-in-blank)
  const [selectedWords, setSelectedWords] = useState([]);
  
  // State for mock response data (this would come from the API in the real app)
  const [responseData, setResponseData] = useState(null);
  
  // State for loading status
  const [isLoading, setIsLoading] = useState(false);
  
  // Exercise type options
  const exerciseTypes = [
    { id: 'multiple_choice', label: 'Multiple Choice' },
    { id: 'fill_in_blank', label: 'Fill in the Blank' },
    { id: 'matching', label: 'Matching' },
    { id: 'sequencing', label: 'Sequencing' },
    { id: 'short_answer', label: 'Short Answer' },
  ];
  
  // Load history example when fill-in-blank is selected
  useEffect(() => {
    if (exerciseType === 'fill_in_blank' && !responseData) {
      // Short delay to show loading state
      setIsLoading(true);
      setTimeout(() => {
        setResponseData({
          exercise_type: 'fill_in_blank',
          ...sampleExercises[0] // Use the history example
        });
        setIsLoading(false);
      }, 500);
    }
  }, [exerciseType, responseData]);
  
  // Handle word selection for fill-in-blank exercises
  const handleWordSelect = (word, newText) => {
    // If new text is provided, update the input text
    if (newText !== undefined) {
      setInputText(newText);
      return;
    }
    
    // Otherwise add the selected word
    if (word && !selectedWords.includes(word)) {
      setSelectedWords([...selectedWords, word]);
    }
  };
  
  // Remove a word from the selected words
  const handleWordRemove = (index) => {
    const newSelectedWords = [...selectedWords];
    newSelectedWords.splice(index, 1);
    setSelectedWords(newSelectedWords);
  };
  
  // Handle exercise type change
  const handleExerciseTypeChange = (e) => {
    const newType = e.target.value;
    setExerciseType(newType);
    
    // Reset state when changing types
    setResponseData(null);
    setSelectedWords([]);
    
    // History example for fill-in-blank will be loaded by the useEffect
  };
  
  // Mock function to simulate API call to LLM
  const generateExercise = () => {
    setIsLoading(true);
    
    // Simulate API delay
    setTimeout(() => {
      // Create mock response based on exercise type
      const mockResponse = generateMockResponse(exerciseType, inputText);
      setResponseData(mockResponse);
      setIsLoading(false);
    }, 1500);
  };
  
  // Generate a fill-in-blank exercise from selected words
  const generateFillInBlankExercise = () => {
    if (!inputText || selectedWords.length === 0) {
      return;
    }
    
    setIsLoading(true);
    
    // Simulate API delay
    setTimeout(() => {
      // Generate passage with blanks
      const { passage, blanks } = generatePassageWithBlanks(inputText, selectedWords);
      
      // Create exercise data
      const exercise = {
        exercise_type: 'fill_in_blank',
        id: `fill-in-blank-${Date.now()}`,
        instructions: 'Fill in the blanks with the correct words.',
        passage,
        blanks,
        caseSensitive: false
      };
      
      setResponseData(exercise);
      setIsLoading(false);
    }, 1000);
  };
  
  // Helper to generate mock responses
  const generateMockResponse = (type, text) => {
    switch (type) {
      case 'multiple_choice':
        return {
          exercise_type: "multiple_choice",
          question: text ? `Based on your input: "${text.substring(0, 30)}...", what is the main concept discussed?` : "Based on the text, what is the main concept discussed?",
          options: [
            `A mock option generated from the input "${text.substring(0, 15)}..."`,
            "Another potential answer based on input",
            "A third option that could be correct",
            "A fourth option to complete the choices"
          ],
          correct_answer: ["Another potential answer based on input"],
          explanation: "This is a mock explanation that would be generated by Alex Ex's AI system. It would provide details about why the correct answer is correct and why the other options are incorrect.",
          max_score: 1,
          grading_type: "auto"
        };
      case 'fill_in_blank':
        // For fill_in_blank, we'll use the manually selected words approach
        if (selectedWords.length > 0) {
          const { passage, blanks } = generatePassageWithBlanks(text, selectedWords);
          return {
            exercise_type: "fill_in_blank",
            instructions: "Fill in the blanks with the correct words.",
            passage,
            blanks,
            caseSensitive: false
          };
        } else {
          // Fallback to history example
          return {
            exercise_type: "fill_in_blank",
            ...sampleExercises[0]
          };
        }
      // Add cases for other exercise types as we implement them
      default:
        return {
          exercise_type: type,
          question: "This is a placeholder for " + type + " exercise",
          // Other fields would depend on exercise type
        };
    }
  };
  
  // Handle exercise submission
  const handleExerciseSubmit = (submissionData) => {
    console.log('Exercise submitted:', submissionData);
    // In a real implementation, this would send the submission to the backend
  };
  
  // Render the appropriate exercise component based on type
  const renderExerciseComponent = () => {
    if (!responseData) return null;
    
    switch (responseData.exercise_type) {
      case 'multiple_choice':
        // Transform the API response to our component's data format
        const multipleChoiceData = transformApiResponseToMultipleChoice(responseData);
        return (
          <MultipleChoiceExercise 
            exercise={multipleChoiceData}
            onSubmit={handleExerciseSubmit}
          />
        );
      case 'fill_in_blank':
        // Transform the API response to our component's data format
        const fillInBlankData = transformApiResponseToFillInBlank(responseData);
        return (
          <FillInBlankExercise 
            exercise={fillInBlankData}
            onSubmit={handleExerciseSubmit}
          />
        );
      // Add cases for other exercise types as we implement them
      default:
        return (
          <div className="bg-white p-4 rounded-md shadow-sm border border-slate-200 mb-4">
            <h3 className="font-medium text-lg mb-3">
              Placeholder for {responseData.exercise_type} exercise
            </h3>
            <p className="text-slate-600">
              This exercise type hasn't been implemented yet.
            </p>
          </div>
        );
    }
  };
  
  // Render the appropriate teacher input interface based on exercise type
  const renderTeacherInputInterface = () => {
    switch (exerciseType) {
      case 'fill_in_blank':
        return (
          <>
            {/* Word Selector Component */}
            <WordSelector
              sourceText={inputText}
              selectedWords={selectedWords}
              onWordSelect={handleWordSelect}
              onWordRemove={handleWordRemove}
            />
            
            {/* Generate Button */}
            <button
              onClick={generateFillInBlankExercise}
              disabled={isLoading || !inputText.trim() || selectedWords.length === 0}
              className={`w-full py-2 px-4 rounded-md font-medium text-white ${
                isLoading || !inputText.trim() || selectedWords.length === 0
                  ? 'bg-blue-300 cursor-not-allowed' 
                  : 'bg-blue-600 hover:bg-blue-700'
              }`}
            >
              {isLoading ? 'Generating...' : 'Generate Custom Exercise'}
            </button>
            
            <p className="text-sm text-slate-500 mt-2">
              The History example is loaded by default. Create your own exercise by selecting words from your text.
            </p>
          </>
        );
      default:
        return (
          <>
            {/* Text Input */}
            <div className="mb-4">
              <label className="block text-sm font-medium text-slate-700 mb-1">
                Source Text
              </label>
              <textarea
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                placeholder="Enter the text from which to generate exercises..."
                className="w-full p-2 border border-slate-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 h-64"
              />
            </div>
            
            {/* Generate Button */}
            <button
              onClick={generateExercise}
              disabled={isLoading || !inputText.trim()}
              className={`w-full py-2 px-4 rounded-md font-medium text-white ${
                isLoading || !inputText.trim() 
                  ? 'bg-blue-300 cursor-not-allowed' 
                  : 'bg-blue-600 hover:bg-blue-700'
              }`}
            >
              {isLoading ? 'Generating...' : 'Generate Exercise'}
            </button>
          </>
        );
    }
  };
  
  return (
    <div className="flex flex-col md:flex-row h-screen bg-slate-50">
      {/* Teacher Input Side */}
      <div className="w-full md:w-1/2 p-4 border-r border-slate-200 overflow-auto">
        <h2 className="text-xl font-semibold mb-4 text-slate-800">Teacher Input</h2>
        
        {/* Exercise Type Selector */}
        <div className="mb-4">
          <label className="block text-sm font-medium text-slate-700 mb-1">
            Exercise Type
          </label>
          <select
            value={exerciseType}
            onChange={handleExerciseTypeChange}
            className="w-full p-2 border border-slate-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
          >
            {exerciseTypes.map(type => (
              <option key={type.id} value={type.id}>
                {type.label}
              </option>
            ))}
          </select>
        </div>
        
        {/* Dynamic Teacher Input Interface */}
        {renderTeacherInputInterface()}
        
        {/* Request Preview (JSON being sent) */}
        <div className="mt-6">
          <h3 className="text-md font-medium text-slate-700 mb-2">Request Data</h3>
          <pre className="bg-slate-100 p-3 rounded-md text-xs overflow-auto max-h-40">
            {JSON.stringify({
              exercise_type: exerciseType,
              source_text: inputText.substring(0, 100) + (inputText.length > 100 ? '...' : ''),
              ...(exerciseType === 'fill_in_blank' && { selected_words: selectedWords })
            }, null, 2)}
          </pre>
        </div>
      </div>
      
      {/* Exercise Display Side */}
      <div className="w-full md:w-1/2 p-4 overflow-auto">
        <h2 className="text-xl font-semibold mb-4 text-slate-800">Exercise Preview</h2>
        
        {isLoading ? (
          <div className="flex justify-center items-center h-64">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
          </div>
        ) : responseData ? (
          <div>
            {/* Exercise Display Component */}
            {renderExerciseComponent()}
            
            {/* Response Data (Debug View) */}
            <div className="mt-6">
              <h3 className="text-md font-medium text-slate-700 mb-2">
                Response Data (Debug View)
              </h3>
              <pre className="bg-slate-100 p-3 rounded-md text-xs overflow-auto max-h-96">
                {JSON.stringify(responseData, null, 2)}
              </pre>
            </div>
          </div>
        ) : (
          <div className="flex justify-center items-center h-64 text-slate-400">
            Generate an exercise to see the preview
          </div>
        )}
      </div>
    </div>
  );
};

export default ExerciseTester;