import React from 'react';
import OptionItem from './OptionItem';

/**
 * Component for displaying a list of options in a Multiple Choice exercise
 * 
 * @component
 * @param {Object} props
 * @param {Array} props.options - The options to display
 * @param {boolean} props.allowMultipleSelections - Whether multiple selections are allowed
 * @param {Array} props.selectedOptionIds - The currently selected option IDs
 * @param {Function} props.onOptionSelect - Callback for when an option is selected
 * @param {boolean} [props.showFeedback] - Whether to show feedback (correct/incorrect indicators)
 */
const OptionsList = ({
  options,
  allowMultipleSelections,
  selectedOptionIds,
  onOptionSelect,
  showFeedback
}) => {
  return (
    <div className="mb-6">
      {/* 
        Map through the options array and render an OptionItem for each one
        AI-INTEGRATION-POINT: This component expects the options array 
        to be generated by Alex's AI system
      */}
      {options.map((option) => (
        <OptionItem
          key={option.id}
          option={option}
          isSelected={selectedOptionIds.includes(option.id)}
          isMultipleSelect={allowMultipleSelections}
          onSelect={() => {
            if (!showFeedback) {
              onOptionSelect(option.id);
            }
          }}
          showFeedback={showFeedback}
        />
      ))}
    </div>
  );
};

export default OptionsList;
