/**
 * Sample data for Multiple Choice exercises
 * This file contains example data that demonstrates the structure expected
 * for Multiple Choice exercises.
 * 
 * AI-INTEGRATION-NOTE: This sample data illustrates where AI-generated content
 * will be inserted. The actual content will be generated by Alex Ex's system.
 */

/**
 * Example of a multiple choice exercise with multiple correct answers
 */
export const multipleChoiceMultipleAnswers = {
  id: "mc-example-1",
  
  // AI-INTEGRATION-POINT: Main question text
  questionText: "Which of the following are examples of renewable energy sources?",
  
  // AI-INTEGRATION-POINT: Optional instructions
  instructions: "Select all that apply.",
  
  allowMultipleSelections: true,
  
  // AI-INTEGRATION-POINT: Options array
  options: [
    {
      id: "option-1",
      // AI-INTEGRATION-POINT: Option text
      text: "Solar power",
      isCorrect: true,
      // AI-INTEGRATION-POINT: Option-specific feedback
      feedback: "Correct! Solar power is a renewable energy source."
    },
    {
      id: "option-2",
      // AI-INTEGRATION-POINT: Option text
      text: "Coal",
      isCorrect: false,
      // AI-INTEGRATION-POINT: Option-specific feedback
      feedback: "Incorrect. Coal is a non-renewable fossil fuel."
    },
    {
      id: "option-3",
      // AI-INTEGRATION-POINT: Option text
      text: "Wind power",
      isCorrect: true,
      // AI-INTEGRATION-POINT: Option-specific feedback
      feedback: "Correct! Wind power is a renewable energy source."
    },
    {
      id: "option-4",
      // AI-INTEGRATION-POINT: Option text
      text: "Natural gas",
      isCorrect: false,
      // AI-INTEGRATION-POINT: Option-specific feedback
      feedback: "Incorrect. Natural gas is a non-renewable fossil fuel."
    }
  ],
  
  // AI-INTEGRATION-POINT: Explanation shown after answer submission
  explanation: "Renewable energy sources are those that can be naturally replenished on a human timescale. Solar and wind power are renewable because they rely on virtually inexhaustible sources, while fossil fuels like coal and natural gas take millions of years to form."
};

/**
 * Example of a multiple choice exercise with a single correct answer
 */
export const multipleChoiceSingleAnswer = {
  id: "mc-example-2",
  
  // AI-INTEGRATION-POINT: Main question text
  questionText: "What is the capital city of France?",
  
  instructions: "Select the correct answer.",
  
  allowMultipleSelections: false,
  
  // AI-INTEGRATION-POINT: Options array
  options: [
    {
      id: "option-1",
      // AI-INTEGRATION-POINT: Option text
      text: "London",
      isCorrect: false,
      // AI-INTEGRATION-POINT: Option-specific feedback
      feedback: "Incorrect. London is the capital of the United Kingdom."
    },
    {
      id: "option-2",
      // AI-INTEGRATION-POINT: Option text
      text: "Berlin",
      isCorrect: false,
      // AI-INTEGRATION-POINT: Option-specific feedback
      feedback: "Incorrect. Berlin is the capital of Germany."
    },
    {
      id: "option-3",
      // AI-INTEGRATION-POINT: Option text
      text: "Paris",
      isCorrect: true,
      // AI-INTEGRATION-POINT: Option-specific feedback
      feedback: "Correct! Paris is the capital of France."
    },
    {
      id: "option-4",
      // AI-INTEGRATION-POINT: Option text
      text: "Madrid",
      isCorrect: false,
      // AI-INTEGRATION-POINT: Option-specific feedback
      feedback: "Incorrect. Madrid is the capital of Spain."
    }
  ],
  
  // AI-INTEGRATION-POINT: Explanation shown after answer submission
  explanation: "Paris is the capital and most populous city of France, with an estimated population of 2.1 million residents."
};

/**
 * Example of a more complex multiple choice exercise 
 * with rich text formatting in the question
 */
export const multipleChoiceWithRichText = {
  id: "mc-example-3",
  
  // AI-INTEGRATION-POINT: Main question text with rich formatting
  // Note: The actual implementation will support HTML or Markdown formatting
  questionText: `<p>Read the following passage and answer the question:</p>
  <blockquote>
    The Renaissance was a period in European history marking the transition from the Middle Ages to modernity and covering the 15th and 16th centuries. It began in Italy and spread to the rest of Europe. The Renaissance was characterized by an emphasis on the individual, a revival of classical learning, and a spirit of innovation and exploration.
  </blockquote>
  <p>Which of the following best describes the Renaissance?</p>`,
  
  allowMultipleSelections: false,
  
  // AI-INTEGRATION-POINT: Options array
  options: [
    {
      id: "option-1",
      text: "A period of religious uniformity and conservatism",
      isCorrect: false,
      feedback: "Incorrect. The Renaissance was characterized by innovation, not conservatism."
    },
    {
      id: "option-2",
      text: "A transitional period emphasizing individuality and classical revival",
      isCorrect: true,
      feedback: "Correct! The Renaissance emphasized the individual and revived classical learning."
    },
    {
      id: "option-3",
      text: "A time of significant technological regression",
      isCorrect: false,
      feedback: "Incorrect. The Renaissance was a time of innovation, not regression."
    },
    {
      id: "option-4",
      text: "A period limited exclusively to Italian art history",
      isCorrect: false,
      feedback: "Incorrect. While the Renaissance began in Italy, it spread throughout Europe and impacted many aspects of society beyond art."
    }
  ],
  
  explanation: "The Renaissance was a critical transitional period in European history that emphasized individuality, revived classical learning, and fostered innovation and exploration. It began in Italy but spread throughout Europe, influencing art, literature, philosophy, science, religion, and politics."
};

// Helper function to transform API response data to our internal structure
export const transformApiResponseToMultipleChoice = (apiData) => {
  // AI-INTEGRATION-POINT: This function will convert the data format
  // from Alex's AI generation to our internal format
  
  return {
    id: apiData.id || `mc-${Date.now()}`,
    questionText: apiData.question || '',
    instructions: apiData.instructions || '',
    allowMultipleSelections: apiData.correct_answer && Array.isArray(apiData.correct_answer) && apiData.correct_answer.length > 1,
    options: (apiData.options || []).map((option, index) => ({
      id: `option-${index + 1}`,
      text: option,
      isCorrect: Array.isArray(apiData.correct_answer) 
        ? apiData.correct_answer.includes(option)
        : apiData.correct_answer === option,
      feedback: '' // API might not provide per-option feedback
    })),
    explanation: apiData.explanation || ''
  };
};
